"""
Initial migrations for gym_api
This file is auto-generated by Django
"""
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gym Branch',
                'verbose_name_plural': 'Gym Branches',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('gym_manager', 'Gym Manager'), ('trainer', 'Trainer'), ('member', 'Member')], default='member', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='gym_api.gymbranch')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'trainer'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_workout_plans', to='gym_api.user')),
                ('gym_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='gym_api.gymbranch')),
            ],
            options={
                'verbose_name': 'Workout Plan',
                'verbose_name_plural': 'Workout Plans',
            },
        ),
        migrations.CreateModel(
            name='WorkoutTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workout_tasks', to='gym_api.user')),
                ('member', models.ForeignKey(limit_choices_to={'role': 'member'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='gym_api.user')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='gym_api.workoutplan')),
            ],
            options={
                'verbose_name': 'Workout Task',
                'verbose_name_plural': 'Workout Tasks',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='gym_api.user')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='gym_api_use_email_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='gym_api_use_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['gym_branch'], name='gym_api_use_gym_br_idx'),
        ),
        migrations.AddIndex(
            model_name='gymbranch',
            index=models.Index(fields=['name'], name='gym_api_gym_name_idx'),
        ),
        migrations.AddIndex(
            model_name='gymbranch',
            index=models.Index(fields=['is_active'], name='gym_api_gym_is_ac_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutplan',
            index=models.Index(fields=['gym_branch', 'created_by'], name='gym_api_wor_gym_br_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutplan',
            index=models.Index(fields=['created_at'], name='gym_api_wor_created_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutTask',
            index=models.Index(fields=['member', 'status'], name='gym_api_wor_member_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutTask',
            index=models.Index(fields=['workout_plan', 'member'], name='gym_api_wor_workout_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutTask',
            index=models.Index(fields=['created_at'], name='gym_api_wor_created_2_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutTask',
            index=models.Index(fields=['due_date'], name='gym_api_wor_due_dat_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'created_at'], name='gym_api_act_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='gym_api_act_created_idx'),
        ),
    ]
